steps:
  # Build and deploy train service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ml-sf-train', './functions/ml-sf-train']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ml-sf-train']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'ml-sf-train'
    - '--image'
    - 'gcr.io/$PROJECT_ID/ml-sf-train'
    - '--region'
    - '${_REGION}'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'MOTHERDUCK_TOKEN=${_MOTHERDUCK_TOKEN},DB_SCHEMA=${_DB_SCHEMA}'

  # Build and deploy predict service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ml-sf-predict', './functions/ml-sf-predict']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ml-sf-predict']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'ml-sf-predict'
    - '--image'
    - 'gcr.io/$PROJECT_ID/ml-sf-predict'
    - '--region'
    - '${_REGION}'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'MOTHERDUCK_TOKEN=${_MOTHERDUCK_TOKEN},DB_SCHEMA=${_DB_SCHEMA}'

images:
  - 'gcr.io/$PROJECT_ID/ml-sf-train'
  - 'gcr.io/$PROJECT_ID/ml-sf-predict'

substitutions:
  _REGION: us-central1
  _DB_SCHEMA: default
